apiVersion: v1
kind: Service
metadata:
  name: dep-green-service
  namespace: green  
spec:
  selector:
    app: dep-v2  
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 80   # Port exposed by the container (in your image)
  type: LoadBalancer
