apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-v2
  labels:
    app: webapp
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      version: v2
  template:
    metadata:
      labels:
        app: webapp
        version: v2
    spec:
      containers:
      - name: webapp
        image: surya9961/k8sdep:v2
        ports:
        - containerPort: 80
