apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-v1
  labels:
    app: webapp
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      containers:
      - name: webapp
        image: surya9961/k8sdep:v1
        ports:
        - containerPort: 80
