apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: LoadBalancer
  selector:
    app: webapp
    version: v1   # Start with blue version
  ports:
    - port: 80
      targetPort: 80
